import React  from "react";
interface ReactChildren {
    props:{
        children: React.ReactNode;
    }
}
const layout = ({children}:ReactChildren) => {
  return (
    <>
    {children}
      <footer className="w-full flex justify-center items-center  md:h-16 p-2 mt-20 border border-yellow-400 ">
        <p className="text-mainGray text-[10px] md:text-md p-0">
          TemoGPT is integrated with the ChatGPT API to display results
          generated by it.
        </p>
      </footer>
    </>
  );
};

export default layout;
