// "use client";
// import { useState, useEffect } from "react";
// import axios from "axios";
// import QuizButtons from "../../../components/QuizButtons";
// const Layout = ({ children }) => {
//   const apiURL = process.env.NEXT_PUBLIC_API_URL;

//   const [categories, setCategories] = useState([]);
//   const [user, setUser] = useState({});
//   const [openQuizzes, setOpenQuizzes] = useState([]);

//   useEffect(() => {
//     axios
//       .get(`${apiURL}/categories`)
//       .then((res) => {
//         const cats = res.data.data.filter((cat) => cat.name !== "programming");

//         setCategories(cats);
//       })
//       .catch((error) => console.log(error));
//     axios
//       .get(`${apiURL}/users/me`)
//       .then((res) => setUser(res.data.user))
//       .catch((error) => console.log(error));
//   }, []);

//   //  get user open quiz
//   useEffect(() => {
//     if (user.userId) {
//       axios
//         .get(`${apiURL}/open-quiz/${user.userId}`)
//         .then((res) => {
//           setOpenQuizzes(res.data.data);
//           console.log(res.data.data);
//         })
//         .catch((error) => console.log(error));
//     }
//   }, [user]);

//   return (
//     <div className="w-screen h-full border-2 border-yellow-300  relative overflow-scroll ">
//       <div className="flex justify-center" dir="">
//         <div className="flex items-center gap-2" dir="rtl">
//           {categories?.map((cat) => {
//             if (openQuizzes?.length === 0) {
//               return (
//                 <QuizButtons
//                   // key={cat.id}
//                   categoryId={cat.id}
//                   quizName={`${cat.name}  اختبار`}
//                 />
//               );
//             }

//             if (
//               openQuizzes[0]?.categoryId === cat.id &&
//               openQuizzes[0]?.openQuiz === true
//             ) {
//               return null;
//             } else if (
//               openQuizzes[1]?.categoryId === cat.id &&
//               openQuizzes[1]?.openQuiz === true
//             ) {
//               return null;
//             } else {
//               return (
//                 <QuizButtons
//                   key={cat.id + 1}
//                   categoryId={cat.id}
//                   quizName={`${cat.name}  اختبار`}
//                 />
//               );
//             }
//           })}
//         </div>
//       </div>
//       {children}

//       <div className="w-full flex justify-center items-center  md:h-16 p-0 mt-2  border border-green-500 absolute bottom-0">
//         <p className="text-mainGray text-[10px] md:text-md p-0">
//           TemoGPT is integrated with the ChatGPT API to display results
//           generated by it.
//         </p>
//       </div>
//     </div>
//   );
// };

// export default Layout;

"use client";
import { useState, useEffect } from "react";
import axios from "axios";
import QuizButtons from "../../../components/QuizButtons";

export default function Layout({ children }) {
  const apiURL = process.env.NEXT_PUBLIC_API_URL;

  const [categories, setCategories] = useState([]);
  const [user, setUser] = useState({});
  const [openQuizzes, setOpenQuizzes] = useState([]);

  useEffect(() => {
    axios
      .get(`${apiURL}/categories`)
      .then((res) => {
        const cats = res.data.data.filter((cat) => cat.name !== "programming");

        setCategories(cats);
      })
      .catch((error) => console.log(error));
    axios
      .get(`${apiURL}/users/me`)
      .then((res) => setUser(res.data.user))
      .catch((error) => console.log(error));
  }, []);

  //  get user open quiz
  useEffect(() => {
    if (user.userId) {
      axios
        .get(`${apiURL}/open-quiz/${user.userId}`)
        .then((res) => {
          setOpenQuizzes(res.data.data);
          console.log(res.data.data);
        })
        .catch((error) => console.log(error));
    }
  }, [user]);

  return (
    <div className="flex flex-col min-h-screen">
      <div className="flex justify-center">
        <div className="flex items-center gap-2" dir="rtl">
          {categories?.map((cat) => {
            if (openQuizzes?.length === 0) {
              return (
                <QuizButtons
                  // key={cat.id}
                  categoryId={cat.id}
                  quizName={`${cat.name}  اختبار`}
                />
              );
            }
            if (
              openQuizzes[0]?.categoryId === cat.id &&
              openQuizzes[0]?.openQuiz === true
            ) {
              return null;
            } else if (
              openQuizzes[1]?.categoryId === cat.id &&
              openQuizzes[1]?.openQuiz === true
            ) {
              return null;
            } else {
              return (
                <QuizButtons
                  key={cat.id + 1}
                  categoryId={cat.id}
                  quizName={`${cat.name}  اختبار`}
                />
              );
            }
          })}
        </div>
      </div>
      {/* Content Section */}
      <main className="flex-grow overflow-auto">{children}</main>

      {/* Footer Section */}
      <div className="bg-gray-50 text-mainGray pt-6 p-4 text-center">
        <p>
          TemoGPT is integrated with the ChatGPT API to display results
          generated by it.
        </p>
      </div>
    </div>
  );
}
